ReferenceError: Can't find variable: i
variable i is local scope in function play(), the variable i in function check() causes this error because it is not declared either in global scope or the function local scope.